name: PHP Sniffer CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Replace with your desired PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit

      # Add more steps for your specific project, like running PHP Sniffer, etc.
