name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          if: success()
          
      - name: Install Node.js dependencies
        run: npm install

      - name: Set up PHP (only for integration tests)
        if: ${{ env.TEST_SCRIPT == 'test:integration' }}
        run: |
          phpenv config-add test/php.ini
          composer global require squizlabs/php_codesniffer:^3.4
          echo "::add-path::$(composer global config bin-dir --absolute)"

      - name: Set up Xvfb (only for Linux)
        if: runner.os == 'Linux' && ${{ env.TEST_SCRIPT == 'test:integration' }}
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run script
        run: npm run ${{ env.TEST_SCRIPT }}
